import type { AlertAction, AlertStats, AuditEvent, DossierResponse, EvidenceRecord, OverviewStats, ProjectFingerprint, ProjectSummary, RiskResponse } from '../types/project';

export const MOCK_OVERVIEW: OverviewStats = {
  total_projects: 80,
  projects_requiring_attention: 28,
  high_risk_signals: 14,
  delayed_projects: 34,
  potential_overlap_signals: 8,
  risk_distribution: {
    low: 32,
    medium: 20,
    high: 14,
    critical: 14,
  },
  top_states: [
    { state: 'Rajasthan', count: 18, avg_risk: 58.4 },
    { state: 'Uttar Pradesh', count: 16, avg_risk: 54.2 },
    { state: 'Maharashtra', count: 14, avg_risk: 49.6 },
    { state: 'Madhya Pradesh', count: 12, avg_risk: 47.1 },
    { state: 'Karnataka', count: 10, avg_risk: 42.8 },
    { state: 'Tamil Nadu', count: 10, avg_risk: 39.5 },
  ],
  work_type_breakdown: [
    { work_type: 'Road Construction', count: 18 },
    { work_type: 'Drinking Water Supply', count: 14 },
    { work_type: 'School Building', count: 12 },
    { work_type: 'Community Hall', count: 10 },
    { work_type: 'Drainage System', count: 8 },
    { work_type: 'Public Toilet', count: 6 },
    { work_type: 'Bridge Construction', count: 5 },
    { work_type: 'Street Lighting', count: 4 },
    { work_type: 'Health Sub-Center', count: 2 },
    { work_type: 'Anganwadi Center', count: 1 },
  ],
  open_alerts: 18,
  escalated_count: 4,
};

export const MOCK_PROJECTS: ProjectSummary[] = [
  {
    id: 101,
    project_id: 'MD101',
    state: 'Delhi',
    district: 'New Delhi',
    constituency: 'New Delhi',
    work_type: 'Solar Panel Installation',
    description: 'Installation of solar panels on government buildings',
    sanctioned_amount: 8000000,
    released_amount: 8000000,
    expenditure: 7500000,
    physical_progress: 100,
    start_date: '2023-01-01',
    expected_completion: '2023-12-31',
    latitude: 28.6139,
    longitude: 77.2090,
    agency: 'Delhi Solar Corp',
    contractor: 'SunTech Solutions',
    risk_score: 5.5,
    confidence_score: 98.0,
    main_signal: 'Project completed successfully on time',
  },
  {
    id: 102,
    project_id: 'MD102',
    state: 'Gujarat',
    district: 'Ahmedabad',
    constituency: 'Ahmedabad East',
    work_type: 'Community Hall',
    description: 'Construction of smart community hall with modern amenities',
    sanctioned_amount: 15000000,
    released_amount: 7500000,
    expenditure: 7000000,
    physical_progress: 45.0,
    start_date: '2023-06-15',
    expected_completion: '2024-06-14',
    latitude: 23.0225,
    longitude: 72.5714,
    agency: 'Ahmedabad Municipal Corporation',
    contractor: 'BuildWell Infra',
    risk_score: 25.0,
    confidence_score: 90.0,
    main_signal: 'Normal progress, on track',
  },
  {
    id: 12,
    project_id: 'MD012',
    state: 'Rajasthan',
    district: 'Jaipur',
    constituency: 'Jaipur Rural',
    work_type: 'Road Construction',
    description: 'Construction of CC road from main highway to village Rampura',
    sanctioned_amount: 4500000,
    released_amount: 4200000,
    expenditure: 3950000,
    physical_progress: 28.5,
    start_date: '2023-04-10',
    expected_completion: '2024-02-15',
    latitude: 26.9124,
    longitude: 75.7873,
    agency: 'Public Works Department (PWD)',
    contractor: 'Shree Balaji Constructions',
    risk_score: 84.7,
    confidence_score: 85.0,
    main_signal: 'High expenditure (87.8%) with severely lagging progress (28.5%)',
  },
  {
    id: 6,
    project_id: 'MD006',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    constituency: 'Varanasi South',
    work_type: 'Drainage System',
    description: 'Construction of covered storm water drain along residential ward 14',
    sanctioned_amount: 3200000,
    released_amount: 3200000,
    expenditure: 3100000,
    physical_progress: 35.0,
    start_date: '2022-11-01',
    expected_completion: '2023-08-30',
    latitude: 25.3176,
    longitude: 82.9739,
    agency: 'Municipal Corporation',
    contractor: 'Ganga Valley Infrastructure',
    risk_score: 82.5,
    confidence_score: 90.0,
    main_signal: 'Severe progress gap of 65.0 percentage points vs expected timeline',
  },
  {
    id: 14,
    project_id: 'MD014',
    state: 'Maharashtra',
    district: 'Pune',
    constituency: 'Pune Central',
    work_type: 'Community Hall',
    description: 'Construction of multipurpose community center in village Khed',
    sanctioned_amount: 6000000,
    released_amount: 5500000,
    expenditure: 5200000,
    physical_progress: 17.8,
    start_date: '2022-06-15',
    expected_completion: '2023-06-15',
    latitude: 18.5204,
    longitude: 73.8567,
    agency: 'Zilla Parishad Pune',
    contractor: 'Sahyadri Engineering Works',
    risk_score: 82.2,
    confidence_score: 95.0,
    main_signal: 'Large progress gap (82.2 pts behind schedule) and 450+ days overdue',
  },
  {
    id: 1,
    project_id: 'MD001',
    state: 'Rajasthan',
    district: 'Jodhpur',
    constituency: 'Jodhpur City',
    work_type: 'Road Construction',
    description: 'Construction of interlocking paver block road in ward 22',
    sanctioned_amount: 2800000,
    released_amount: 2800000,
    expenditure: 2433200,
    physical_progress: 32.3,
    start_date: '2022-01-15',
    expected_completion: '2023-01-14',
    latitude: 26.2389,
    longitude: 73.0243,
    agency: 'Jodhpur Development Authority',
    contractor: 'Apex Infra Solutions',
    risk_score: 81.0,
    confidence_score: 95.0,
    main_signal: 'High expenditure (86.9%) vs physical progress (32.3%) + duplicate pair MD047',
  },
  {
    id: 10,
    project_id: 'MD010',
    state: 'Madhya Pradesh',
    district: 'Indore',
    constituency: 'Indore Central',
    work_type: 'School Building',
    description: 'Construction of 4 additional classrooms in Government Higher Secondary School',
    sanctioned_amount: 5200000,
    released_amount: 5200000,
    expenditure: 4900000,
    physical_progress: 28.8,
    start_date: '2023-01-10',
    expected_completion: '2023-11-30',
    latitude: 22.7196,
    longitude: 75.8577,
    agency: 'MP Public Works Dept',
    contractor: 'Malwa Buildtech Corp',
    risk_score: 80.2,
    confidence_score: 95.0,
    main_signal: 'Critical timeline delay with 94.2% funds disbursed',
  },
  {
    id: 19,
    project_id: 'MD019',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    constituency: 'Lucknow East',
    work_type: 'Drinking Water Supply',
    description: 'Installation of deep tube well and 50000L overhead water storage tank',
    sanctioned_amount: 3800000,
    released_amount: 3800000,
    expenditure: 3200000,
    physical_progress: 54.2,
    start_date: '2023-03-01',
    expected_completion: '2023-12-15',
    latitude: 26.8467,
    longitude: 80.9462,
    agency: 'UP Jal Nigam',
    contractor: 'Awadh Utilities & Pipes',
    risk_score: 73.5,
    confidence_score: 88.0,
    main_signal: 'Spending velocity 1.8x higher than regional peer average',
  },
  {
    id: 47,
    project_id: 'MD047',
    state: 'Rajasthan',
    district: 'Jodhpur',
    constituency: 'Jodhpur City',
    work_type: 'Road Construction',
    description: 'Interlocking paver block road construction near ward 22 community hall',
    sanctioned_amount: 2750000,
    released_amount: 2750000,
    expenditure: 2100000,
    physical_progress: 40.0,
    start_date: '2022-04-10',
    expected_completion: '2023-03-15',
    latitude: 26.2412,
    longitude: 73.0265,
    agency: 'Jodhpur Development Authority',
    contractor: 'Apex Infra Solutions',
    risk_score: 72.8,
    confidence_score: 90.0,
    main_signal: 'Multi-signal geographic & entity overlap with project MD001 (0.3km distance)',
  },
  {
    id: 25,
    project_id: 'MD025',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    constituency: 'Bengaluru South',
    work_type: 'Public Toilet',
    description: 'Construction of modern automated e-toilet block near transit terminal',
    sanctioned_amount: 1800000,
    released_amount: 1800000,
    expenditure: 1650000,
    physical_progress: 60.0,
    start_date: '2023-05-15',
    expected_completion: '2023-10-31',
    latitude: 12.9716,
    longitude: 77.5946,
    agency: 'BBMP Bengaluru',
    contractor: 'Karnataka Urban Tech',
    risk_score: 68.2,
    confidence_score: 82.0,
    main_signal: 'Release ratio 100% with stalled completion over past 120 days',
  },
  {
    id: 31,
    project_id: 'MD031',
    state: 'Tamil Nadu',
    district: 'Madurai',
    constituency: 'Madurai Central',
    work_type: 'Street Lighting',
    description: 'Installation of 120 solar LED street lighting units in rural habitations',
    sanctioned_amount: 1500000,
    released_amount: 1500000,
    expenditure: 1100000,
    physical_progress: 75.0,
    start_date: '2023-08-01',
    expected_completion: '2024-01-30',
    latitude: 9.9252,
    longitude: 78.1198,
    agency: 'District Rural Development Agency',
    contractor: 'SunPower Tamil Nadu',
    risk_score: 48.6,
    confidence_score: 80.0,
    main_signal: 'Moderate timeline delay (45 days) within normal operational variance',
  },
  {
    id: 42,
    project_id: 'MD042',
    state: 'Maharashtra',
    district: 'Nagpur',
    constituency: 'Nagpur South',
    work_type: 'School Building',
    description: 'Renovation of science laboratory and computer room in Zilla Parishad School',
    sanctioned_amount: 2200000,
    released_amount: 2200000,
    expenditure: 1750000,
    physical_progress: 82.0,
    start_date: '2023-06-01',
    expected_completion: '2024-01-15',
    latitude: 21.1458,
    longitude: 79.0882,
    agency: 'Zilla Parishad Nagpur',
    contractor: 'Vidarbha Civil Works',
    risk_score: 34.2,
    confidence_score: 92.0,
    main_signal: 'Progress closely aligned with expenditure; low statistical deviation',
  },
  {
    id: 55,
    project_id: 'MD055',
    state: 'Karnataka',
    district: 'Mysuru',
    constituency: 'Mysuru North',
    work_type: 'Drinking Water Supply',
    description: 'Laying of 3.5km feeder water pipeline to Chamundi foothills settlement',
    sanctioned_amount: 4100000,
    released_amount: 4100000,
    expenditure: 3950000,
    physical_progress: 96.0,
    start_date: '2023-02-10',
    expected_completion: '2023-11-20',
    latitude: 12.2958,
    longitude: 76.6394,
    agency: 'Karnataka Water Supply Board',
    contractor: 'Cauvery Water Infrastructure',
    risk_score: 18.5,
    confidence_score: 98.0,
    main_signal: 'Healthy work near completion; all inspection benchmarks verified',
  },
  {
    id: 64,
    project_id: 'MD064',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'Chennai South',
    work_type: 'Anganwadi Center',
    description: 'Construction of dedicated model Anganwadi center with child-friendly amenities',
    sanctioned_amount: 1950000,
    released_amount: 1950000,
    expenditure: 1900000,
    physical_progress: 100.0,
    start_date: '2023-01-05',
    expected_completion: '2023-09-30',
    latitude: 13.0827,
    longitude: 80.2707,
    agency: 'Greater Chennai Corporation',
    contractor: 'Marina Civil Construction',
    risk_score: 12.0,
    confidence_score: 99.0,
    main_signal: 'Work fully completed and certified within sanctioned budget',
  },
];

export const MOCK_FINGERPRINTS: Record<string, ProjectFingerprint> = {
  MD001: {
    financial: {
      sanctioned_amount: 2800000,
      released_amount: 2800000,
      expenditure: 2433200,
      expenditure_ratio: 86.9,
      release_ratio: 100.0,
      spending_velocity: 3120.5,
    },
    progress: {
      physical_progress: 32.3,
      expected_progress: 100.0,
      progress_gap: 67.7,
    },
    temporal: {
      start_date: '2022-01-15',
      expected_completion: '2023-01-14',
      planned_duration_days: 364,
      elapsed_days: 780,
      delay_days: 416,
    },
    geographic: {
      latitude: 26.2389,
      longitude: 73.0243,
    },
    entity: {
      agency: 'Jodhpur Development Authority',
      contractor: 'Apex Infra Solutions',
    },
  },
};

export const MOCK_RISK: Record<string, RiskResponse> = {
  MD001: {
    risk_score: 81.0,
    confidence_score: 95.0,
    breakdown: {
      rule_score: 85.0,
      ml_anomaly_score: 78.4,
      similarity_score: 82.0,
      peer_score: 76.5,
    },
    why_flagged: [
      'High expenditure (86.9%) vs physical progress (32.3%)',
      'Progress gap: 67.7 percentage points behind timeline expectation',
      'Delayed 416 days past sanctioned completion deadline',
      'High spatial and textual similarity detected with project MD047 (0.3km away)',
      'Contractor entity cluster: Apex Infra Solutions holds 4 other flagged projects',
    ],
  },
};

export const MOCK_DOSSIERS: Record<string, DossierResponse> = {
  MD001: {
    project_id: 'MD001',
    risk_score: 81.0,
    confidence_score: 95.0,
    why_flagged: [
      'High expenditure (86.9%) vs physical progress (32.3%)',
      'Progress gap: 67.7 percentage points behind timeline expectation',
      'Delayed 416 days past sanctioned completion deadline',
      'Potentially overlapping duplicate project MD047 detected within 300 meters',
      'Contractor entity cluster: Apex Infra Solutions has 3 high-risk flagged road works',
    ],
    supporting_evidence: {
      expenditure_ratio: 86.9,
      release_ratio: 100.0,
      spending_velocity: 3120.5,
      physical_progress: 32.3,
      expected_progress: 100.0,
      progress_gap: 67.7,
      delay_days: 416,
      sanctioned_amount: 2800000,
    },
    similar_projects: [
      {
        project_id: 'MD047',
        description: 'Interlocking paver block road construction near ward 22 community hall',
        distance_km: 0.28,
        text_similarity: 0.74,
        signals: [
          'Geo proximity < 0.5km',
          'Identical contractor (Apex Infra Solutions)',
          'Overlapping execution timeline (2022–2023)',
          'Matching work category (Road Construction)',
        ],
        match_strength: 0.88,
      },
    ],
    peer_comparisons: [
      {
        peer_group_size: 18,
        metric: 'Expenditure / Progress Ratio',
        project_value: 2.69,
        peer_median: 1.05,
        peer_q1: 0.85,
        peer_q3: 1.25,
        deviation: 'above_iqr',
      },
      {
        peer_group_size: 18,
        metric: 'Timeline Delay (Days)',
        project_value: 416,
        peer_median: 45,
        peer_q1: 0,
        peer_q3: 90,
        deviation: 'above_iqr',
      },
      {
        peer_group_size: 18,
        metric: 'Spending Velocity (₹/day)',
        project_value: 3120.5,
        peer_median: 2150.0,
        peer_q1: 1800.0,
        peer_q3: 2400.0,
        deviation: 'above_iqr',
      },
    ],
    recommended_verification: [
      'Conduct immediate physical on-site measurement of paver block road in Ward 22.',
      'Cross-examine GPS coordinates and boundary limits with sanctioned works in MD047 to ensure no double-invoicing on identical road stretches.',
      'Audit muster rolls and material vouchers justifying ₹24.33L expenditure against 32.3% physical completion.',
      'Summon executing agency (JDA) and contractor (Apex Infra Solutions) for recorded explanation on 416-day delay.',
    ],
    disclaimer:
      'This dossier identifies risk signals for authorised human verification. It does not establish fraud or misconduct.',
  },
};

// V2 Mock Data

export const MOCK_EVIDENCE: Record<string, EvidenceRecord[]> = {
  MD101: [
    {
      id: 1,
      project_id: 101,
      submitted_by: 'Inspector Sharma',
      evidence_type: 'inspector_note',
      description: 'Site visit on 15 Sep 2026: Road base layer incomplete despite 86.9% expenditure reported. Only partial grading observed over 1.2km stretch.',
      submitted_at: '2026-09-15T10:30:00',
    },
    {
      id: 2,
      project_id: 101,
      submitted_by: 'Inspector Sharma',
      evidence_type: 'site_photo',
      description: 'Photographic evidence of incomplete road surface near Jaipur-Ajmer NH junction. Gravel exposed, no bitumen layer applied.',
      file_path: '/evidence/md101_site_photo_01.jpg',
      latitude: 26.8546,
      longitude: 75.7217,
      submitted_at: '2026-09-15T10:45:00',
    },
  ],
};

export const MOCK_ALERTS: Record<string, AlertAction> = {
  MD101: {
    id: 1,
    project_id: 101,
    current_status: 'evidence_submitted',
    assigned_to: 'Inspector Sharma',
    opened_at: '2026-09-10T08:00:00',
  },
  MD102: {
    id: 2,
    project_id: 102,
    current_status: 'open',
    opened_at: '2026-09-10T08:00:00',
  },
  MD103: {
    id: 3,
    project_id: 103,
    current_status: 'escalated',
    assigned_to: 'Inspector Verma',
    opened_at: '2026-09-10T08:00:00',
  },
};

export const MOCK_AUDIT_EVENTS: Record<string, AuditEvent[]> = {
  MD101: [
    {
      id: 1,
      project_id: 101,
      actor: 'system',
      action: 'alert_opened',
      details: JSON.stringify({ risk_score: 82.5, reason: 'Auto-opened: risk score exceeds threshold.' }),
      timestamp: '2026-09-10T08:00:00',
      integrity_hash: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
    },
    {
      id: 2,
      project_id: 101,
      actor: 'Inspector Sharma',
      action: 'alert_status_changed',
      details: JSON.stringify({ from_status: 'open', to_status: 'under_review' }),
      timestamp: '2026-09-12T09:15:00',
      integrity_hash: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3',
    },
    {
      id: 3,
      project_id: 101,
      actor: 'Inspector Sharma',
      action: 'evidence_submitted',
      details: JSON.stringify({ evidence_type: 'inspector_note', description: 'Site visit completed.' }),
      timestamp: '2026-09-15T10:30:00',
      integrity_hash: 'c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
    },
  ],
};

export const MOCK_ALERT_STATS: AlertStats = {
  open_alerts: 18,
  under_review: 6,
  evidence_submitted: 4,
  escalated: 4,
  resolved: 2,
  dismissed: 1,
};
